name: Release

on:
  push:
    tags:
      - "v*"

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Go
        uses: actions/setup-go@v5
        with:
          go-version: "1.25"

      - name: Build binaries
        run: make build-android

      - name: Upload Release
        uses: softprops/action-gh-release@v2
        with:
          files: smsgateway/bin/*
